version: '3'

# includes:
#   packages:
#     taskfile: ./PackageTasks.yaml

#   brews:
#     taskfile: ./BrewTasks.yaml

tasks:

  apply-packages:
    internal: true
    summary: Downloads and installs packages and brews.
    platforms: [windows]
    cmds:
      - task: packages:apply
      - task: brews:apply

  dump-packages:
    internal: true
    platforms: [windows]
    cmds:
      - task: brews:dump

  configure:
    internal: true
    platforms: [windows]
    cmds:
      - cmd: ./darwin/configure.sh
