version: '3'

includes:
  winget:
    taskfile: ./WingetTasks.yaml
  chocolatey:
    taskfile: ./ChocolateyTasks.yaml
  additional:
    taskfile: ./AdditionalAppTasks.yaml

tasks:

  debloat:
    platforms: [windows]
    desc: "Removes bloatware using Windows 10 Debloater: https://github.com/Sycnex/Windows10Debloater"
    cmds:
      - cmd: PowerShell.exe -File ./windows/debloat.ps1

  apply-packages:
    internal: true
    platforms: [windows]
    cmds:
      - task: winget:apply
      - task: chocolatey:apply
      - task: additional:install

  dump-packages:
    internal: true
    platforms: [windows]
    cmds:
      - task: chocolatey:dump
      - task: winget:dump

  configure:
    internal: true
    platforms: [windows]
    cmds:
      - cmd: PowerShell.exe -File ./windows/configure.ps1
