version: '3'

includes:
  winget:
    taskfile: ./WingetTasks.yaml

tasks:

  apply-packages:
    internal: true
    platforms: [windows]
    cmds:
      - task: winget:apply

  dump-packages:
    internal: true
    platforms: [windows]
    cmds:
      - task: winget:dump

  configure:
    internal: true
    platforms: [windows]
    cmds:
      - cmd: PowerShell.exe -File configure.ps1
