tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "act"
brew "bash"
brew "cowsay"
brew "fortune"
brew "gh"
brew "git"
brew "go"
brew "gum"
brew "helm"
brew "hugo"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "python@3.10"
brew "libfido2"
brew "lolcat"
brew "lsusb"
brew "mas"
brew "minikube"
brew "neofetch"
brew "neovim"
brew "node"
brew "pnpm"
brew "openssh"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "derailed/k9s/k9s"
cask "clion"
cask "datagrip"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "fork"
cask "goland"
cask "hyper"
cask "keycastr"
cask "little-snitch"
cask "lulu"
cask "mos"
cask "onyx"
cask "rectangle"
cask "rider"
cask "signal"
cask "spotify"
cask "stats"
cask "visual-studio-code"
cask "webstorm"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Bitwarden", id: 1352778147
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tailscale", id: 1475387142
mas "Yubico Authenticator", id: 1497506650
