version: '3'

dotenv: ['.env']

includes:
  system:
    taskfile: ./{{OS}}/Taskfile.yaml

vars:
  BACKUP_DIR: $HOME/.dotfile_backup

tasks:

  default:
    cmds:
      - task --list

  apply:
    desc: Downloads necessary packages and applications, configures various settings, installs plugins, and creates symlinks to the config files managed in this git repository.
    cmds:
      - task: system:apply-packages
      - task: clone-repos
      - task: create-symlinks
      - task: configure

  clone-repos:
    desc: Clones any git repositories defined in repos.yaml, and ensures any already cloned repos are up-to-date.
    vars:
      COMMANDS:
        sh: yq '.repos[] | "sh ./scripts/install-from-git.sh " + .url + " " + .dir + " " + .ref' repos.yaml

    cmds:
      - platforms: [linux, darwin]
        cmd: |
          {{.COMMANDS}}

  configure:
    desc: Configures the local environment, as well as various first-party and third-party applications.
    cmds:
      - interactive: true
        task: system:configure

  dump:
    desc: Writes the state of the local environment (currently just packages and plugins) to this git repository.
    cmds:
      - task: system:dump-packages

  import-ssh-keys:
    - platforms: [linux, darwin]
      desc: Imports SSH keys.
      interactive: true
      cmd: ./scripts/import_ssh_keys.sh
  
  create-symlinks:
    desc: Creates symlinks for the config files managed in this git repository so that they can be read by their intended application.
    vars:
      BACKUP_COMMANDS: 
        sh: yq '.links[] comments="" | .links[] | "test -e " + .destination + " && mv " + .destination + " {{.BACKUP_DIR}}/$(basename " + .source + ")-backup-$(date +%Y-%m-%d_%H:%M:%S)"' symlinks.yaml
      LINK_COMMANDS:
        # sh: yq '.links[] comments="" | .links[] | "[[ -f " + .source + " ]] && mkdir -p \"$(dirname " + .destination + ")\" || mkdir -p " + .destination + " && ln -s -f \"$(realpath " + .source + ")\" " + .destination' symlinks.yaml
        sh: yq '.links[] comments="" | .links[] | "mkdir -p \"$(dirname " + .destination + ")\" && ln -s -f \"$(realpath " + .source + ")\" " + .destination' symlinks.yaml

    cmds:
      - platforms: [linux, darwin]
        cmd: |
          mkdir -p {{.BACKUP_DIR}}
          {{.BACKUP_COMMANDS}}
          {{.LINK_COMMANDS}}
