tap "octopusdeploy/taps" 
brew "octopusdeploy/taps/octopus-cli"
cask "1password-cli"
cask "azure-data-studio"
cask "powershell"
cask "slack"
cask "meetingbar"
vscode "octopusdeploy.vscode-octopusdeploy"