version: '3'

includes:
  packages:
    taskfile: ./PackageTasks.yaml

  brews:
    taskfile: ./BrewTasks.yaml

tasks:

  apply-packages:
    internal: true
    platforms: [darwin]
    cmds:
      - task: packages:apply
      - task: brews:apply
      - task: apply-patches

  install-sfmono-fonts:
    desc: Downloads the SF Mono font and patches it with NerdFonts.
    platforms: [darwin]
    cmds:
      - ./darwin/install-sf-mono-nerdfont.sh

  dump-packages:
    internal: true
    platforms: [darwin]
    cmds:
      - task: brews:dump

  configure:
    internal: true
    platforms: [darwin]
    cmds:
      - cmd: ./darwin/configure.sh

