version: '3'

tasks:
  apply-plugins:
    desc: Ensures all plugins defined in the plugins file are installed.
    vars:
      INSTALL_COMMAND:
        sh: "yq '.plugins[]' ./vscode/plugins.yaml | awk -F': ' '{print \"code --install-extension\", $1, \"--force\"}'"
    cmds:
      - "{{.INSTALL_COMMAND}}"

  dump-plugins:
    desc: Updates the plugins file with a list of installed plugins.
    vars:
      PLUGINS:
        sh: printf '"%s", ' $(code --list-extensions) | sed 's/, $//'
    cmds:
      - echo "⌨️ Dumping VSCode Plugins"
      - yq -i ' .plugins = [{{.PLUGINS}}]' ./vscode/plugins.yaml
