[build]
cpus = 2
image = "ghcr.io/apple/container-builder-shim/builder:0.12.0"
memory = "2048mb"
rosetta = true

[container]
cpus = 4
memory = "4gb"

[dns]

[kernel]
binaryPath = "opt/kata/share/kata-containers/vmlinux-6.18.15-186"
url = "https://github.com/kata-containers/kata-containers/releases/download/3.28.0/kata-static-3.28.0-arm64.tar.zst"

[machine]
cpus = 7
homeMount = "rw"
memory = "16gb"
virtualization = false

[network]

[registry]
domain = "docker.io"

[vminit]
image = "ghcr.io/apple/containerization/vminit:0.35.0"
